### ISSUE TITLE
小哥！想请问一下时序数据的标注方式和标注工具？

### ISSUE THREAD

**Issue by RobertXiaobinW** [madao33/ECG-Classfier#1]
想请问ECG信号是怎么标注的呢

**Comment by madao33** [comment]
关于数据集标注的方式和标注工具，一般是找专业人士识别心电或者其他的信号，然后记录一个结果，例如存在异常，或者正常，标注工具不是很清楚，如果是简单的，可以直接按照顺序把结果列在excel表格中
