### ISSUE TITLE
mlModels.ipy failing 

### ISSUE THREAD

**Issue by ghost-operative-itachi** [madao33/ECG-Classfier#2]
everything with this code shoots the error
-------------
for index in range(len(y_train)):
    y_train[index] = np.where(num2class == y_train[index][0][0])[0]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-0ee6f5544ae0> in <module>
      1 for index in range(len(y_train)):
----> 2     y_train[index] = np.where(num2class == y_train[index][0][0])[0]

TypeError: 'int' object is not subscriptable

**Comment by madao33** [comment]
before the wrong code, check your `y_train`, should be like this form below:
```python
>>> y_train

array([[list(['STTC'])],
       [list(['MI'])],
       [list(['NORM'])],
       ...,
       [list(['CD', 'NORM'])],
       [list(['NORM'])],
       [list(['NORM'])]], dtype=object)
```

dataPreprocess.ipynb is not so good, you can try to rewrite one and be aware of your data type.
