### ISSUE TITLE
老哥你好，我也是做ECG的。

### ISSUE THREAD

**Issue by PGCJ** [madao33/ECG-Classfier#3]
我想请问下，网络上哪些精度特别高的是真的吗？特别是对于小样本的，各种98%+，我怎么做也做不出来。而且很多都是用超类来实现，对应独立的类型（比如房颤，房扑这种小类），我很难达到高精度。请问能指点一下吗？

**Comment by madao33** [comment]
如果是按照准确率的话，确实可以达到这么高的精度，因为有很多正常心电，但是如果以F1分数作为评价标准的话，可能最高听实验室的专业人士说只有0.85左右吧，f1分数是平均调和平均数，用这个指标判断比较好

**Comment by PGCJ** [comment]
> 

意思是，如果但看其中一个的话，是不可能每一个都高精度的对吗？很多所谓的高精度，是因为比如norm类型很多，整体看起来很高，实际上单独的精度可能很低的？我最近用ptb-xl，做rhythm的七分类，其中只有3个分类能90+，其他都是30-60的水平，一直再想办法提高。（哭泣脸）

**Comment by madao33** [comment]
是这样的，俺也这样

**Comment by PGCJ** [comment]
> 

感谢老哥，我还以为只是我操作有问题。
有空多联系，再次谢谢老哥。

**Comment by madao33** [comment]
没事儿，快跑，这个项目难搞，基本上能用的trick都被别人用了

**Comment by PGCJ** [comment]
没办法呀，导师安排了任务，我打算集成一下各种方法，看看能不能混一篇随便哪一个核心就跑路。主要是这个能做的太少了，数据量和其他任务比起来，太少了。

**Comment by madao33** [comment]
你尝试一下手动提取信号，或者结合病人的其他生理信息整一下，另外换个模型，什么transoformer机制啥的弄一下吧

**Comment by PGCJ** [comment]
手动提取是指的，比如一张图片，用图像处理方法去提取导联吗？
模型我现在用过了resnet ，preactresnet，agg之类的，基本上都是resnet最好。transform我把我现在弄的弄guiyi了，我就去看。

**Comment by PGCJ** [comment]
老哥不好意思，又来叨唠你了。
我结合之前看的文献关于用R波识别还有你对于R波的处理，然后处理出来的数据（分类是五个超类，NORM CD  HYP  MI  STTC ）。
然后用ResNet34，我修改成1D。效果不佳，F1指标只有80,20,50,60,33.精度也只有70.
然后我用你的机器学习的随机森林的方法测试居然有90。感觉就很离谱，这正常吗？

**Comment by madao33** [comment]
不应该吧，ResNet的一些参数可能需要多试一下，你看一下训练误差曲线，调整一下架构和超参数，再试一试吧

**Comment by PGCJ** [comment]
我能理解为，用R波进行分割，把每一张5000*12的图片变成500*12的图片，然后进行划分吗？

**Comment by madao33** [comment]
我是直接划分的信号，不是转换的图片，就是一维的信号，有的也不是一个心电节拍，有的是好几个心电节拍，也就是3-6s的数据左右，如果采样率是500Hz，那么划分的信号长度就是500xN长度的信号，N可以是3-6

**Comment by PGCJ** [comment]
明白了。我也是这样的，不过我是用500hz划分为500长度的。我试试500*3~6，可能对于500hz而言500的长度太小了。

**Comment by madao33** [comment]
可行

**Comment by PGCJ** [comment]
老哥好，如果一张500hz的图（长度5000），您划分成多个图以后，是随机放在测试集和训练集中。还是测试集是测试集的数据增强，训练集是训练集的数据增强

**Comment by PGCJ** [comment]
哥你做的时候考虑了多标签么

**Comment by madao33** [comment]
如果说为了防止数据泄露，正常来说先划分训练集和测试集，然后再来分段，不然一条心电，训练集有，测试集也有，那就有点造假了

**Comment by PGCJ** [comment]
> 如果说为了防止数据泄露，正常来说先划分训练集和测试集，然后再来分段，不然一条心电，训练集有，测试集也有，那就有点造假了

我也是这样理解的。之前有些论文就是这样性能虚高的。我感觉这个方向太困难了。
